version: '3.8'

services:
  web:
    build:
      context: .
    
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
